オブジェクト指向2
HAL-223/06_car pull request #2
Opened 2020-02-20 14:25 UTC by HAL-223

2020-02-20 14:32 UTC, HAL-223 commented
お疲れ様です！
継承部分が上手く出来ていないのか表示する所がアクセスして見ると空になってしまいます。
parent::infomationを使いやってみたんですが表示されず、今はそのまま上で使っていたecho部分を持ってきました。
Carクラスのようにname,number,colorをもう一度取得し直したほうば良いのでしょうか？

2020-02-21 07:22 UTC, kazu-taka requested changes
@HAL-223 
コメントしたので確認お願いします:bow:

2020-02-21 07:22 UTC, kazu-taka commented on index.php
> +  public function __construct($passenger) {
@HAL-223 
コンストラクタはnewした時(`new Taxi('クラウンのタクシー', '222', 'black')`)の項目と一致させなければいけません。
今回はnewした時の項目はCarクラスの時と一緒なので、Taxiクラスにコンストラクタを追加する必用なないです✨

2020-02-21 07:22 UTC, kazu-taka commented on index.php
> +  }
@HAL-223 
setPassengerとgetPassengerはどこからも呼ばれていないような気がするので、不用なコードは削除お願いします:bow:

2020-02-21 07:22 UTC, kazu-taka commented on index.php
> +$taxi1->setpickUp(3);
@HAL-223 
新たに`setpickUp`メソッドを作成していますが、以下のコードが動くようにコードを追加するという課題になるので、以下のコード以外でコードを追加するのは、タクシークラスだけ(`class Taxi extends Car {  〜 }`の間だけ)になります！
```php
// 以下を実行した時にエラーがでないようにして下さい
// Carクラスのインスタンスを生成
// 引数 : 車名、車体番号、カラー
$car1 = new Car('ランクル', 100, 'black');

// 車の情報を表示
echo $car1->infomation();
echo '<br>';
echo '<hr>';

// Taxiクラスのインスタンスを生成
$taxi1 = new Taxi('クラウンのタクシー', 222, 'black');

// 3人乗車
$taxi1->pickUp(3);

// タクシーの情報表示を表示
echo $taxi1->infomation();
echo '<br>';

// 2人降車
$taxi1->lower(2);
echo '<br>';

// 一人降車
$taxi1->lower(2);
```

2020-02-21 07:22 UTC, kazu-taka commented on index.php
> +  }
@HAL-223 
`private $passeger;`を定義しているので、インスタンス($taxi1等)は乗車人数を保持することが可能です。
あとはpickUpとlowerメソッドでそれぞれ人数を足したり引いたりすればOKとなります✨

2020-02-21 14:43 UTC, HAL-223 commented on index.php
> +$taxi1->setpickUp(3);
@kazu-taka
setpickUpをpickUpだけにしてしまうと
不明なエラー：未定義のメソッドタクシーの呼び出し::ピックアップ（）/var/www/public/exercise/06_car/index.phpで： 124スタックトレース：＃0 {main}が/var/www/public/exercise/06_car/index.phpの124行目にスローされます
になってしまい、get、set付けて試した結果setだとエラーが出ないのでこれで続けたんです、、、

2020-02-21 15:33 UTC, kazu-taka commented on index.php
> +$taxi1->setpickUp(3);
@HAL-223 
エラーの内容は日本語に翻訳してます？
もししているのであれば変更しないようにお願いします！
メソッド名や変数名まで翻訳されてしまうので。
「未定義のメソッドタクシーの呼び出し::ピックアップ」はそのままで、`◯◯.pickUp`をやろうとしているのに、Taxiクラスに`def pickUp`が定義されていないからです！
今後、エラーメッセージの内容がピンとこない場合は遠慮なく聞いて下さい✨

2020-02-21 17:01 UTC, HAL-223 commented on index.php
> +$taxi1->setpickUp(3);
@kazu-taka
エラー表示は日本語に変更していました。
今後気を付けます。
def pickUpとは何ですか(;_;)？
pickupはset,getで定義されているわけでは無いのでしょうか？

2020-02-21 21:23 UTC, kazu-taka commented on index.php
> +$taxi1->setpickUp(3);
@HAL-223 
ごめんなさい！！
`def pickUp`はrubyの場合で、phpの場合は`public function pickUp`でした^^;
しかも`◯◯.pickUp`もrubyの書き方でした...
pickUpとlowerは`インスタンス->pickUp(3);`と`インスタンス->lower(2);`と記述されているので、タクシークラスの中に、メソッドとして定義する必用があります！
なんかrubyのコードで説明してしまって、混乱させちゃいましたね:bow:
伝わりますかね！？
もう一度クラスのあたりのカリキュラムを見てもらって、今回の部分はどこに当てはまるのか確認してもらえるといいのかもしれないです！
https://23seiki.gitbook.io/php/php/14

2020-02-22 15:25 UTC, HAL-223 commented on index.php
> +$taxi1->setpickUp(3);
@kazu-taka
一旦カリキュラムで復習しながら今の課題を確認して進めてみたんですが、エラーが変わらずタクシークラスの表示が何も出ないままです。
passengerで保持してからの使い方もよくわからないです。
今の状態を一度プルリクしました(;_;)

2020-02-26 13:37 UTC, Arisaarisa commented on index.php
>    public function setPickUp($pickUp) {
ここも下でインスタンスがpickupなのでメソッドはpickupです！
引数は値と関連するので$passengerになります！

2020-02-26 13:37 UTC, Arisaarisa commented on index.php
> +    public function getPickUp() {
取得は違ってくるのでgetpickupメソッドは不要です！

2020-02-26 13:37 UTC, Arisaarisa commented on index.php
>    public function setLower($lower) {
ここもsetlowerではなくlower
引数もpickupと同様です！

2020-02-26 13:37 UTC, Arisaarisa commented on index.php
>      $this->lower = $lower;
ここは`もし 今のpassergerの人数から0以上のpassengerが引ける`場合、
複合演算子で計算して降りた人数を表示。
それ以外は"降車人数に誤りがあります"

2020-02-26 13:37 UTC, Arisaarisa commented on index.php
>      return $this->lower;
ここでgetlowerではなくpraivate function getpassenger passengerの拾得してください！

2020-02-26 14:05 UTC, HAL-223 commented on index.php
>    public function setPickUp($pickUp) {
@Arisaarisa setもgetもpickupとlowerには不要ということでしょうか？今pickupの所は
public function pickUp() {
    return $this->$passenger + $this->PickUp;
    }
に変えているんですがこれも違いますよね(;_;)？

2020-02-28 15:58 UTC, HAL-223 commented
@kazu-taka 
@Arisaarisa 
なぜタクシークラスのname,number,colorが取得されていないのか、
'2人降車しました。'が出ておらず、'降車人数に誤りがあります。'が2文でてしまうのは何故かがわからないです。

2020-02-29 01:10 UTC, Arisaarisa commented on index.php
> +    return $this->$passenger + $this->PickUp;
この辺りの書き方って覚えてますか？！
ここは乗客を乗せるだけなのでsetと同じ内容だけで大丈夫です！
hint
$this->passenger = 引数(値になる)

https://23seiki.gitbook.io/php/php/14#11-personkurasuwo

2020-02-29 01:10 UTC, Arisaarisa commented on index.php
> +    if ($this->$passenger - $this->lower > 0) {
if (今のpassengerから$passengerを引く  0以上の場合)

hint
($this->************ - ************* >= 0)

2020-02-29 01:10 UTC, Arisaarisa commented on index.php
> +      $this->$passenger - $this->lower = $passenger;
メソッド内で使うのはプロパティになるのでlowerは使わないです！
ここは今の乗客から値の乗客を引きます！
<img width="747" alt="課題_08_オブジェクト指向の練習2_-_php" src="https://user-images.githubusercontent.com/45112341/75597218-8c81b280-5ad7-11ea-9d85-c9ca80f1ff03.png">

2020-02-29 01:10 UTC, Arisaarisa commented on index.php
> +}
private でカプセル化したら
`書き込みメソッド`だけではなく`読み取りメソッド`もないと出力されません！

https://23seiki.gitbook.io/php/php/13#3-sounarutonoyabishihadouyatteyarebaindaga

hint
public function getPassenger() {
   return  **********************
}

2020-02-29 01:10 UTC, Arisaarisa commented on index.php
> +    echo "車の車種:" . $this->name  . "のタクシー、" . "車体番号:" . $this->number . "、" . "カラー:" . $this->color . "、" . "乗車人数は" . $this->passenger . "人です。";
ここで$this->でアクセスするのは`読み取りしたメソッド`たちです！

2020-03-01 13:45 UTC, HAL-223 commented
乗車人数は表示できました！
ですが、今は"乗車人数に誤りがあります。"が表示されなくなってしまいました。
頭で上手く整理ができなくて、、、。
アドバイスお願いします。

2020-03-02 01:45 UTC, Arisaarisa commented on index.php
> +      $this->passenger - $passenger = $passenger;
この部分はもとのpassengerからpassengerを引いてまたもとのpassengerに代入しないといけないので
`-=`になります！

`$a -= $b | a-bの演算結果をaに代入する`
よって

`$this->passenger -= $passenger;`

です！

2020-03-02 07:19 UTC, Arisaarisa commented
![LGTM](https://cdn.lgtmoon.dev/images/10452)

2020-03-02 13:40 UTC, merged